/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.craftcosta.jailrules.rpgcraftcosta.gui.logic.resources;


/**
 *
 * @author jail
 */
public enum EnumQuestItems {
    ANVIL("logic/resources/items/"+"anvil.png","ANVIL",145,0),
    ANVIL_SLIGHTLY_DAMAGED("logic/resources/items/"+"anvil.png","ANVIL",145,1),
    ANVIL_VERY_DAMAGED("logic/resources/items/"+"anvil.png","ANVIL",145,2),    
    APPLE("logic/resources/items/"+ "apple.png","APPLE",260,0),
    ACACIA_FENCE_GATE("logic/resources/items/"+"acacia_fence_gate.png","ACACIA_FENCE_GATE",187,0),
    ACACIA_FENCE("logic/resources/items/"+"acacia_fence.png","ACACIA_FENCE",192,0),
    ACTIVATOR_RAIL("logic/resources/items/"+"activator_rail.png","ACTIVATOR_RAIL",157,0),
    ACACIA_DOOR("logic/resources/items/"+"acacia_door.png","ACACIA_DOOR_ITEM",430,0),
    ACACIA_STAIRS("logic/resources/items/"+"acacia_stairs.png","ACACIA_STAIRS",163,0),
    ARMOR_STAND("logic/resources/items/"+"armor_stand.png","ARMOR_STAND",416,0),
    ARROW("logic/resources/items/"+"arrow.png","ARROW",262,0),
    BEDROCK("logic/resources/items/"+"bedrock.png","BEDROCK",7,0),
    BROWN_MUSHROOM("logic/resources/items/"+"brown_mushroom.png","BROWN_MUSHROOM",39,0),
    BRICK("logic/resources/items/"+"brick.png","BRICK",336,0),
    BOOKSHELF("logic/resources/items/"+"bookshelf.png","BOOKSHELF",47,0),
    BRICK_STAIRS("logic/resources/items/"+"brick_stairs.png","BRICK_STAIRS",108,0),
    BREWING_STAND("logic/resources/items/"+"brewing_stand.png","BREWING_STAND",379,0),
    BIRCH_STAIRS("logic/resources/items/"+"birch_stairs.png","BIRCH_STAIRS",135,0),
    BEACON("logic/resources/items/"+"beacon.png","BEACON",138,0),
    BIRCH_FENCE_GATE("logic/resources/items/"+"birch_fence_gate.png","BIRCH_FENCE_GATE",184,0),
    BIRCH_FENCE("logic/resources/items/"+"birch_fence.png","BIRCH_FENCE",189,0),
    BOW("logic/resources/items/"+"bow.png","BOW",261,0),
    BOAT("logic/resources/items/"+"boat.png","BOAT",333,0),
    BUCKET("logic/resources/items/"+"bucket.png","BUCKET",325,0),
    BONE("logic/resources/items/"+"bone.png","BONE",352,0),
    BOWL("logic/resources/items/"+"bowl.png","BOWL",281,0),
    BOOK("logic/resources/items/"+"book.png","BOOK",340,0),
    BED("logic/resources/items/"+"bed.png","BED",355,0),
    BLAZE_POWDER("logic/resources/items/"+"blaze_powder.png","BLAZE_POWDER",377,0),
    BOOK_AND_QUILL("logic/resources/items/"+"writable_book.png","WRITABLE_BOOK",386,0),
    BAKED_POTATO("logic/resources/items/"+"baked_potato.png","BAKED_POTATO",393,0),
    
    BLACK_BANNER("logic/resources/items/"+"banner.png","BANNER",425,0),
    RED_BANNER("logic/resources/items/"+"banner_1.png","BANNER",425,1),
    GREEN_BANNER("logic/resources/items/"+"banner_2.png","BANNER",425,2),
    BROWN_BANNER("logic/resources/items/"+"banner_3.png","BANNER",425,3),
    BLUE_BANNER("logic/resources/items/"+"banner_4.png","BANNER",425,4),
    PURPLE_BANNER("logic/resources/items/"+"banner_5.png","BANNER",425,5),
    CYAN_BANNER("logic/resources/items/"+"banner_6.png","BANNER",425,6),
    LIGHT_GRAY_BANNER("logic/resources/items/"+"banner_7.png","BANNER",425,7),
    GRAY_BANNER("logic/resources/items/"+"banner_8.png","BANNER",425,8),
    PINK_BANNER("logic/resources/items/"+"banner_9.png","BANNER",425,9),
    LIME_BANNER("logic/resources/items/"+"banner_10.png","BANNER",425,10),
    YELLOW_BANNER("logic/resources/items/"+"banner_11.png","BANNER",425,11),
    LIGHT_BLUE_BANNER("logic/resources/items/"+"banner_12.png","BANNER",425,12),
    MAGENTA_BANNER("logic/resources/items/"+"banner_13.png","BANNER",425,13),
    ORANGE_BANNER("logic/resources/items/"+"banner_14.png","BANNER",425,14),
    WHITE_BANNER("logic/resources/items/"+"banner_15.png","BANNER",425,15),
    
    BIRCH_DOOR("logic/resources/items/"+"birch_door.png","BIRCH_DOOR",428,0),
    BLAZE_ROD("logic/resources/items/"+"blaze_rod.png","BLAZE_ROD",369,0),
    BREAD("logic/resources/items/"+"bread.png","BREAD",297,0),
    BARRIER("logic/resources/items/"+"barrier.png","BARRIER",166,0),
    COBBLESTONE("logic/resources/items/"+"cobblestone.png","COBBLESTONE",4,0),
    COAL_ORE("logic/resources/items/"+"coal_ore.png","COAL_ORE",16,0),
    CHEST("logic/resources/items/"+"chest.png","CHEST",54,0),
    CACTUS("logic/resources/items/"+"cactus.png","CACTUS",81,0),
    CLAY_BLOCK("logic/resources/items/"+"clay_block.png","CLAY",82,0),
    CAULDRON("logic/resources/items/"+"cauldron.png","CAULDRON",380,0),
    CAKE("logic/resources/items/"+"cake.png","CAKE",354,0),
    COCOA("logic/resources/items/"+"cocoa.png","COCOA",127,0),
    
    COOKED_FISH("logic/resources/items/"+"cooked_fished.png","COOKED_FISHED",350,0),
    COOKED_SALMON("logic/resources/items/"+"cooked_fished_1.png","COOKED_FISHED",350,1),
    COOKED_CLOWNFISH("logic/resources/items/"+"cooked_fished_2.png","COOKED_FISHED",350,2),
    COOKED_PUFFERFISH("logic/resources/items/"+"cooked_fished_3.png","COOKED_FISHED",350,3),
    
    COAL("logic/resources/items/"+"coal.png","COAL",263,0),
    CHARCOAL("logic/resources/items/"+"coal_1.png","COAL",263,1),
    
    WHITE_CARPET("logic/resources/items/"+"carpet.png","CARPET",171,0),
    ORANGE_CARPET("logic/resources/items/"+"carpet_1.png","CARPET",171,1),
    MAGENTA_CARPET("logic/resources/items/"+"carpet_2.png","CARPET",171,2),
    LIGHT_BLUE_CARPET("logic/resources/items/"+"carpet_3.png","CARPET",171,3),
    YELLOW_CARPET("logic/resources/items/"+"carpet_4.png","CARPET",171,4),
    LIME_CARPET("logic/resources/items/"+"carpet_5.png","CARPET",171,5),
    PINK_CARPET("logic/resources/items/"+"carpet_6.png","CARPET",171,6),
    GREY_CARPET("logic/resources/items/"+"carpet_7.png","CARPET",171,7),
    LIGHT_GRAY_CARPET("logic/resources/items/"+"carpet_8.png","CARPET",171,8),
    CYAN_CARPET("logic/resources/items/"+"carpet_9.png","CARPET",171,9),
    PURPLE_CARPET("logic/resources/items/"+"carpet_10.png","CARPET",171,10),
    BLUE_CARPET("logic/resources/items/"+"carpet_11.png","CARPET",171,11),
    BROWN_CARPET("logic/resources/items/"+"carpet_12.png","CARPET",171,12),
    GREEN_CARPET("logic/resources/items/"+"carpet_13.png","CARPET",171,13),
    RED_CARPET("logic/resources/items/"+"carpet_14.png","CARPET",171,14),
    BLACK_CARPET("logic/resources/items/"+"carpet_15.png","CARPET",171,15),
    
    COMMAND_BLOCK("logic/resources/items/"+"command_block.png","COMMAND",137,0),
    
    COBBLESTONE_WALL("logic/resources/items/"+"cobblestone_wall.png","COBBLESTONE_WALL",139,0),
    MOSSY_COBBLESTONE_WALL("logic/resources/items/"+"cobblestone_wall_1.png","COBBLESTONE_WALL",139,1),
    
    COAL_BLOCK("logic/resources/items/"+"coal_block.png","COAL_BLOCK",173,0),
    
    
    
    CLAY_BALL("logic/resources/items/"+"clay_ball.png","CLAY_BALL",337,0),
    COMPASS("logic/resources/items/"+"compass.png","COMPASS",345,0),
    COOKIE("logic/resources/items/"+"cookie.png","COOKIE",357,0),
    COOKED_CHICKEN("logic/resources/items/"+"cooked_chicken.png","COOKED_CHICKEN",366,0),
    CARROT("logic/resources/items/"+"carrot.png","CARROT",391,0),
    COOKED_RABBIT("logic/resources/items/"+"cooked_rabbit.png","COOKED_RABBIT",412,0),
    COOKED_BEEF("logic/resources/items/"+"cooked_beef.png","COOKED_BEEF",364,0),
    CARROT_STICK("logic/resources/items/"+"carrot_on_a_stick.png","CARROT_STICK",398,0),
    COOKED_MUTTON("logic/resources/items/"+"cooked_mutton.png","COOKED_MUTTON",424,0),
    COMMAND_MINECART("logic/resources/items/"+"command_block_minecart.png","COMMAND_MINECART",422,0),
    COBBLESTONE_STAIRS("logic/resources/items/"+"cobblestone_stairs.png","COBBLESTONE_STAIRS",67,0),
    
    DIRT("logic/resources/items/"+"dirt.png","DIRT",3,0),
    COARSE_DIRT("logic/resources/items/"+"dirt_1.png","DIRT",3,1),
    PODZOL("logic/resources/items/"+"dirt_2.png","DIRT",3,2),
    
    DISPENSER("logic/resources/items/"+"dispenser.png","DISPENSER",23,0),
    DAYLIGHT_DETECTOR("logic/resources/items/"+"daylight_detector.png","DAYLIGHT_DETECTOR",151,0),
    DRAGON_EGG("logic/resources/items/"+"dragon_egg.png","DRAGON_EGG",122,0),
    DROPPER("logic/resources/items/"+"dropper.png","DROPPER",158,0),
    DARK_OAK_STAIRS("logic/resources/items/"+"dark_oak_stairs.png","DARK_OAK_STAIRS",164,0),
    
    SUNFLOWER("logic/resources/items/"+"double_plant.png","DOUBLE_PLANT",175,0),
    LILAC("logic/resources/items/"+"double_plant_1.png","DOUBLE_PLANT",175,1),
    DOUBLE_TALLGRASS("logic/resources/items/"+"double_plant_2.png","DOUBLE_PLANT",175,2),
    LARGE_FERN("logic/resources/items/"+"double_plant_3.png","DOUBLE_PLANT",175,3),
    ROSE_BUSH("logic/resources/items/"+"double_plant_4.png","DOUBLE_PLANT",175,4),
    PEONY("logic/resources/items/"+"double_plant_5.png","DOUBLE_PLANT",175,5),
    
    DARK_OAK_FENCE_GATE("logic/resources/items/"+"dark_oak_fence_gate.png","DARK_OAK_FENCE_GATE",186,0),
    DOUBLE_RED_SANDSTONE_SLAB("logic/resources/items/"+"double_stone_slab2.png","DOUBLE_STONE_SLAB2",181,0),
    DARK_OAK_FENCE("logic/resources/items/"+"dark_oak_fence.png","DARK_OAK_FENCE",191,0),
    DIAMOND("logic/resources/items/"+"diamond.png","DIAMOND",264,0),
    
    
    DIAMOND_BARDING("logic/resources/items/"+"diamond_horse_armor.png","DIAMOND_BARDING",419,0),
    DIODE("logic/resources/items/"+"repeater.png","REPEATER",356,0),
    DARK_OAK_DOOR("logic/resources/items/"+"dark_oak_door.png","DARK_OAK_DOOR",431,0),
    DETECTOR_RAIL("logic/resources/items/"+"detector_rail.png","DETECTOR_RAIL",28,0),
    DIAMOND_ORE("logic/resources/items/"+"diamond_ore.png","DIAMOND_ORE",56,0),
    DIAMOND_BLOCK("logic/resources/items/"+"diamond_block.png","DIAMOND_BLOCK",57,0),
    
    DEAD_SHRUB("logic/resources/items/"+"tallgrass.png","TALLGRASS",31,0),
    TALL_GRASS("logic/resources/items/"+"tallgrass_1.png","TALLGRASS",31,1),
    FERN("logic/resources/items/"+"tallgrass_2.png","TALLGRASS",31,2),
    DEAD_BUSH("logic/resources/items/"+"deadbush.png","DEADBUSH",32,0),
    
    ENCHANTMENT_TABLE("logic/resources/items/"+"enchanting_table.png","ENCHANTING_TABLE",116,0),
    
    ENDER_STONE("logic/resources/items/"+"end_stone.png","ENDER_STONE",121,0),
    EMERALD_ORE("logic/resources/items/"+"emerald_ore.png","EMERALD_ORE",129,0),
    ENDER_CHEST("logic/resources/items/"+"ender_chest.png","ENDER_CHEST",130,0),
    EXP_BOTTLE("logic/resources/items/"+"experience_bottle.png","EXPERIENCE_BOTTLE",384,0),
    ENDER_PEARL("logic/resources/items/"+"ender_pearl.png","ENDER_PEARL",368,0),
    EGG("logic/resources/items/"+"egg.png","EGG",344,0),
    EMERALD("logic/resources/items/"+"emerald.png","EMERALD",388,0),
    EMPTY_MAP("logic/resources/items/"+"map.png","MAP",395,0),
    ENCHANTED_BOOK("logic/resources/items/"+"enchanted_book.png","ENCHANTED_BOOK",403,0),
    EXPLOSIVE_MINECART("logic/resources/items/"+"tnt_minecart.png","TNT_MINECART",407,0),
    EYE_OF_ENDER("logic/resources/items/"+"ender_eye.png","ENDER_EYE",381,0),
    EMERALD_BLOCK("logic/resources/items/"+"emerald_block.png","EMERALD_BLOCK",133,0),
    FURNACE("logic/resources/items/"+"furnace.png","FURNACE",61,0),
    OAK_FENCE("logic/resources/items/"+"fence.png","FENCE",85,0),
    OAK_FENCE_GATE("logic/resources/items/"+"fence_gate.png","FENCE_GATE",107,0),
    FLOWER_POT("logic/resources/items/"+"flower_pot.png","FLOWERPOT",390,0),
    FLINT_AND_STEEL("logic/resources/items/"+"flint_and_steel.png","FLINT_AND_STEEL",259,0),
    FEATHER("logic/resources/items/"+"feather.png","FEATHER",288,0),
    FIRE_CHARGE("logic/resources/items/"+"fire_charge.png","FIREBALL",385,0),
    FLINT("logic/resources/items/"+"flint.png","FLINT",318,0),
    FISHING_ROD("logic/resources/items/"+"fishing_rod.png","FISHING_ROD",346,0),
    FERMENTED_SPIDER_EYE("logic/resources/items/"+"fermented_spider_eye.png","FERMENTED_SPIDER_EYE",376,0),
    FIREWORK("logic/resources/items/"+"fireworks.png","FIREWORK",401,0),
    FIREWORK_CHARGE("logic/resources/items/"+"firework_charge.png","FIREWORK_CHARGE",402,0),
    GRASS("logic/resources/items/"+"grass.png","GRASS",2,0),
    GRAVEL("logic/resources/items/"+"gravel.png","GRAVEL",13,0),
    GOLD_ORE("logic/resources/items/"+"gold_ore.png","GOLD_ORE",14,0),
    GLASS("logic/resources/items/"+"glass.png","GLASS",20,0),
    GOLD_BLOCK("logic/resources/items/"+"gold_block.png","GOLD_BLOCK",41,0),
    GLOWSTONE("logic/resources/items/"+"glowstone.png","GLOWSTONE",89,0),
    GRILLED_PORK("logic/resources/items/"+"cooked_porkchop.png","COOKED_PORKCHOP",320,0),
    
    GOLD_PRESSURE_PLATE("logic/resources/items/"+"light_weighted_pressure_plate.png","GOLD_PLATE",147,0),
    GOLD_INGOT("logic/resources/items/"+"gold_ingot.png","GOLD_INGOT",266,0),
    GOLDEN_APPLE("logic/resources/items/"+"golden_apple.png","GOLDEN_APPLE",322,0),
    ENCHANTED_GOLDEN_APPLE("logic/resources/items/"+"golden_apple1.png","GOLDEN_APPLE",322,1),
    GLOWSTONE_DUST("logic/resources/items/"+"glowstone_dust.png","GLOWSTONE_DUST",348,0),
    GHAST_TEAR("logic/resources/items/"+"ghast_tear.png","GHAST_TEAR",370,0),
    GOLD_NUGGET("logic/resources/items/"+"gold_nugget.png","GOLD_NUGGET",371,0),
    GLASS_BOTTLE("logic/resources/items/"+"glass_bottle.png","GLASS_BOTTLE",374,0),
    GOLDEN_CARROT("logic/resources/items/"+"golden_carrot.png","GOLDEN_CARROT",396,0),
    GOLD_BARDING("logic/resources/items/"+"golden_horse_armor.png","GOLDEN_HORSE_ARMOR",418,0),
    
    RECORD_13("logic/resources/items/"+"record_13.png","RECORD_13",2256,0),
    RECORD_CAT("logic/resources/items/"+"record_cat.png","RECORD_CAT",2257,0),
    RECORD_BLOCKS("logic/resources/items/"+"record_blocks.png","RECORD_BLOCKS",2258,0),
    RECORD_CHIRP("logic/resources/items/"+"record_chirp.png","RECORD_CHIRP",2259,0),
    RECORD_FAR("logic/resources/items/"+"record_far.png","RECORD_FAR",2260,0),
    RECORD_MALL("logic/resources/items/"+"record_mall.png","RECORD_MALL",2261,0),
    RECORD_MELLOHI("logic/resources/items/"+"record_mellohi.png","RECORD_MELLOHI",2262,0),
    RECORD_STAL("logic/resources/items/"+"record_stal.png","RECORD_STAL",2263,0),
    RECORD_STRAD("logic/resources/items/"+"record_strad.png","RECORD_STRAD",2264,0),
    RECORD_WARD("logic/resources/items/"+"record_ward.png","RECORD_WARD",2265,0),
    RECORD_11("logic/resources/items/"+"record_11.png","RECORD_11",2266,0),
    RECORD_WAIT("logic/resources/items/"+"record_wait.png","RECORD_WAIT",2267,0),
    
    RED_MUSHROOM_BLOCK("logic/resources/items/"+"red_mushroom_block.png","RED_MUSHROOM_BLOCK",99,0),
    BROWN_MUSHROOM_BLOCK("logic/resources/items/"+"brown_mushroom_block.png","BROWN_MUSHROOM_BLOCK",100,0),
    HOPPER("logic/resources/items/"+"hopper.png","HOPPER",154,0),
    HAY_BLOCK("logic/resources/items/"+"hay_block.png","HAY_BLOCK",170,0),
    HARDENED_CLAY("logic/resources/items/"+"hardened_clay.png","HARDENED_CLAY",172,0),
    
    HOPPER_MINECART("logic/resources/items/"+"hopper_minecart.png","HOPPER_MINECART",408,0),
    IRON_ORE("logic/resources/items/"+"iron_ore.png","IRON_ORE",15,0),
    IRON_BLOCK("logic/resources/items/"+"iron_block.png","IRON_BLOCK",42,0),
    ICE("logic/resources/items/"+"ice.png","ICE",79,0),
    IRON_FENCE("logic/resources/items/"+"iron_bars.png","IRON_BARS",101,0),
    IRON_PRESSURE_PLATE("logic/resources/items/"+"heavy_weighted_pressure_plate.png","IRON_PLATE",148,0),
    IRON_TRAPDOOR("logic/resources/items/"+"iron_trapdoor.png","IRON_TRAPDOOR",167,0),
    
    IRON_INGOT("logic/resources/items/"+"iron_ingot.png","IRON_INGOT",265,0),
    
    
    IRON_DOOR("logic/resources/items/"+"iron_door.png","IRON_DOOR",330,0),
    
    INK_SACK("logic/resources/items/"+"dye.png","DYE",351,0),
    ROSE_RED_DYE("logic/resources/items/"+"dye_1.png","DYE",351,1),
    CACTUS_GREEN_DYE("logic/resources/items/"+"dye_2.png","DYE",351,2),
    COCOA_BEAN("logic/resources/items/"+"dye_3.png","DYE",351,3),
    LAPIS_LAZULI("logic/resources/items/"+"dye_4.png","DYE",351,4),
    PURPLE_DYE("logic/resources/items/"+"dye_5.png","DYE",351,5),
    CYAN_DYE("logic/resources/items/"+"dye_6.png","DYE",351,6),
    LIGHT_GRAY_DYE("logic/resources/items/"+"dye_7.png","DYE",351,7),
    GRAY_DYE("logic/resources/items/"+"dye_8.png","DYE",351,8),
    PINK_DYE("logic/resources/items/"+"dye_9.png","DYE",351,9),
    LIME_DYE("logic/resources/items/"+"dye_10.png","DYE",351,10),
    DANDELLION_YELLOW_DYE("logic/resources/items/"+"dye_11.png","DYE",351,11),
    LIGHT_BLUE_DYE("logic/resources/items/"+"dye_12.png","DYE",351,12),
    MAGENTA_DYE("logic/resources/items/"+"dye_13.png","DYE",351,13),
    ORANGE_DYE("logic/resources/items/"+"dye_14.png","DYE",351,14),
    BONE_MEAL("logic/resources/items/"+"dye_15.png","DYE",351,15),
    
    ITEM_FRAME("logic/resources/items/"+"item_frame.png","ITEM_FRAME",389,0),
    IRON_BARDING("logic/resources/items/"+"iron_horse_armor.png","IRON_HORSE_ARMOR",417,0),
    JUNGLE_DOOR("logic/resources/items/"+"jungle_door.png","JUNGLE_DOOR",429,0),
    JUNGLE_FENCE_GATE("logic/resources/items/"+"jungle_fence_gate.png","JUNGLE_FENCE_GATE",185,0),
    JUNGLE_WOOD_STAIRS("logic/resources/items/"+"jungle_stairs.png","JUNGLE_STAIRS",136,0),
    JACK_O_LANTERN("logic/resources/items/"+"lit_pumpkin.png","LIT_PUMPKIN",91,0),
    JUKEBOX("logic/resources/items/"+"jukebox.png","JUKEBOX",84,0),
    JUNGLE_FENCE("logic/resources/items/"+"jungle_fence.png","JUNGLE_FENCE",190,0),
    
    OAK_LOG("logic/resources/items/"+"log.png","LOG",17,0),
    SPRUCE_LOG("logic/resources/items/"+"log_1.png","LOG",17,1),
    BIRCH_LOG("logic/resources/items/"+"log_2.png","LOG",17,2),
    JUNGLE_LOG("logic/resources/items/"+"log_3.png","LOG",17,3),
    
    ACACIA_LOG("logic/resources/items/"+"log2.png","LOG_2",162,0),
    DARK_OAK_LOG("logic/resources/items/"+"log2_1.png","LOG_2",162,1),
    
    OAK_LEAVES("logic/resources/items/"+"leaves.png","LEAVES",18,0),
    SPRUCE_LEAVES("logic/resources/items/"+"leaves_1.png","LEAVES",18,0),
    BIRCH_LEAVES("logic/resources/items/"+"leaves_2.png","LEAVES",18,0),
    JUNGLE_LEAVES("logic/resources/items/"+"leaves_3.png","LEAVES",18,0),
    ACACIA_LEAVES("logic/resources/items/"+"leaves_4.png","LEAVES2",161,0),
    DARK_OAK_LEAVES("logic/resources/items/"+"leaves_5.png","LEAVESw2",161,1),
    
    LAPIS_ORE("logic/resources/items/"+"lapis_ore.png","LAPIS_ORE",21,0),
    LAPIS_BLOCK("logic/resources/items/"+"lapis_block.png","LAPIS_BLOCK",22,0),
    
    LADDER("logic/resources/items/"+"ladder.png","LADDER",65,0),
    LEVER("logic/resources/items/"+"lever.png","LEVER",69,0),
    
    SLIME_BLOCK("logic/resources/items/"+"slime.png","SLIME_BLOCK",165,0),
    LEASH("logic/resources/items/"+"lead.png","LEAD",420,0),
    LAVA_BUCKET("logic/resources/items/"+"lava_bucket.png","LAVA_BUCKET",327,0),
    LEATHER("logic/resources/items/"+"leather.png","LEATHER",334,0),
    
    STONE_MONSTER_EGG("logic/resources/items/"+"monster_egg.png","MONSTER_EGGS",97,0),
    COBBLESTONE_MONSTER_EGG("logic/resources/items/"+"monster_egg_1.png","MONSTER_EGGS",97,1),
    STONE_BRICK_MONSTER_EGG("logic/resources/items/"+"monster_egg_2.png","MONSTER_EGGS",97,2),
    MOSSY_STONE_BRICK_MONSTER_EGG("logic/resources/items/"+"monster_egg_3.png","MONSTER_EGGS",97,3),
    CRACKED_STONE_MONSTER_EGG("logic/resources/items/"+"monster_egg_4.png","MONSTER_EGGS",97,4),
    CHISELED_STONE_MONSTER_EGG("logic/resources/items/"+"monster_egg_5.png","MONSTER_EGGS",97,5),
    
    MUSHROOM_SOUP("logic/resources/items/"+"mushroom_stew.png","MUSHROOM_STEW",282,0),
    MYCELIUM("logic/resources/items/"+"mycelium.png","MYCELIUM",110,0),

    MELON_BLOCK("logic/resources/items/"+"melon_block.png","MELON_BLOCK",103,0),
    
    MOSSY_COBBLESTONE("logic/resources/items/"+"mossy_cobblestone.png","MOSSY_COBBLESTONE",48,0),
    FILLED_MAP("logic/resources/items/"+"filled_map.png","FILLED_MAP",358,0),
    RAW_MUTTON("logic/resources/items/"+"mutton.png","MUTTON",423,0),
    MAGMA_CREAM("logic/resources/items/"+"magma_cream.png","MAGMA_CREAM",378,0),
    
    CREEPER_SPAWN_EGG("logic/resources/items/"+"spawn_egg_50.png","SPAWN_EGG",383,50),
    SKELETON_SPAWN_EGG("logic/resources/items/"+"spawn_egg_51.png","SPAWN_EGG",383,51),
    SPIDER_SPAWN_EGG("logic/resources/items/"+"spawn_egg_52.png","SPAWN_EGG",383,52),
    ZOMBIE_SPAWN_EGG("logic/resources/items/"+"spawn_egg_54.png","SPAWN_EGG",383,54),
    SLIME_SPAWN_EGG("logic/resources/items/"+"spawn_egg_55.png","SPAWN_EGG",383,55),
    GHAST_SPAWN_EGG("logic/resources/items/"+"spawn_egg_56.png","SPAWN_EGG",383,56),
    PIGMEN_SPAWN_EGG("logic/resources/items/"+"spawn_egg_57.png","SPAWN_EGG",383,57),
    ENDERMAN_SPAWN_EGG("logic/resources/items/"+"spawn_egg_58.png","SPAWN_EGG",383,58),
    CAVESPIDER_SPAWN_EGG("logic/resources/items/"+"spawn_egg_59.png","SPAWN_EGG",383,59),
    SILVERFISH_SPAWN_EGG("logic/resources/items/"+"spawn_egg_60.png","SPAWN_EGG",383,60),
    BLAZE_SPAWN_EGG("logic/resources/items/"+"spawn_egg_61.png","SPAWN_EGG",383,61),
    MAGMACUBE_SPAWN_EGG("logic/resources/items/"+"spawn_egg_62.png","SPAWN_EGG",383,62),
    BAT_SPAWN_EGG("logic/resources/items/"+"spawn_egg_65.png","SPAWN_EGG",383,65),
    WITCH_SPAWN_EGG("logic/resources/items/"+"spawn_egg_66.png","SPAWN_EGG",383,66),
    ENDERMITE_SPAWN_EGG("logic/resources/items/"+"spawn_egg_67.png","SPAWN_EGG",383,67),
    GUARDIAN_SPAWN_EGG("logic/resources/items/"+"spawn_egg_68.png","SPAWN_EGG",383,68),
    PIG_SPAWN_EGG("logic/resources/items/"+"spawn_egg_90.png","SPAWN_EGG",383,90),
    SHEEP_SPAWN_EGG("logic/resources/items/"+"spawn_egg_91.png","SPAWN_EGG",383,91),
    COW_SPAWN_EGG("logic/resources/items/"+"spawn_egg_92.png","SPAWN_EGG",383,92),
    CHICKEN_SPAWN_EGG("logic/resources/items/"+"spawn_egg_93.png","SPAWN_EGG",383,93),
    SQUID_SPAWN_EGG("logic/resources/items/"+"spawn_egg_94.png","SPAWN_EGG",383,94),
    WOLF_SPAWN_EGG("logic/resources/items/"+"spawn_egg_95.png","SPAWN_EGG",383,95),
    MUSHROOMCOW_SPAWN_EGG("logic/resources/items/"+"spawn_egg_96.png","SPAWN_EGG",383,96),
    OCELOT_SPAWN_EGG("logic/resources/items/"+"spawn_egg_98.png","SPAWN_EGG",383,98),
    HORSE_SPAWN_EGG("logic/resources/items/"+"spawn_egg_100.png","SPAWN_EGG",383,100),
    RABBIT_SPAWN_EGG("logic/resources/items/"+"spawn_egg_101.png","SPAWN_EGG",383,101),
    VILLAGER_SPAWN_EGG("logic/resources/items/"+"spawn_egg_120.png","SPAWN_EGG",383,120),
    
    MELON_SLICE("logic/resources/items/"+"melon.png","MELON",360,0),
    MILK_BUCKET("logic/resources/items/"+"milk_bucket.png","MILK_BUCKET",335,0),
    MINECART("logic/resources/items/"+"minecart.png","MINECART",328,0),
    MELON_SEEDS("logic/resources/items/"+"melon_seeds.png","MELON_SEEDS",362,0),
    NAME_TAG("logic/resources/items/"+"name_tag.png","NAME_TAG",421,0),
    NETHER_STAR("logic/resources/items/"+"nether_star.png","NETHER_STAR",399,0),
    NETHER_STALK("logic/resources/items/"+"nether_wart.png","NETHER_STALK",372,0),
    NETHER_BRICK("logic/resources/items/"+"nether_brick.png","NETHER_BRICK",112,0),
    NETHER_FENCE("logic/resources/items/"+"nether_brick_fence.png","NETHER_FENCE",113,0),
    NETHER_BRICK_STAIRS("logic/resources/items/"+"nether_brick_stairs.png","NETHER_BRICK_STAIRS",114,0),
    NETHERRACK("logic/resources/items/"+"netherrack.png","NETHERRACK",87,0),
    NETHER_BRICK_ITEM("logic/resources/items/"+"netherbrick.png","NETHER_BRICK_ITEM",405,0),
    NOTE_BLOCK("logic/resources/items/"+"noteblock.png","NOTE_BLOCK",25,0),
    OBSIDIAN("logic/resources/items/"+"obsidian.png","OBSIDIAN",49,0),
    POWERED_RAIL("logic/resources/items/"+"golden_rail.png","POWERED_RAIL",27,0),
    PORK("logic/resources/items/"+"porkchop.png","PORKCHOP",319,0),
    PUMPKIN("logic/resources/items/"+"pumpkin.png","PUMPKIN",86,0),
    POTATO("logic/resources/items/"+"potato.png","POTATO",392,0),
    
    PRISMARINE_BLOCK("logic/resources/items/"+"prismarine.png","PRISMARINE",168,0),
    PRISMARINE_BRICK("logic/resources/items/"+"prismarine_1.png","PRISMARINE",168,1),
    DARK_PRISMARINE("logic/resources/items/"+"prismarine_2.png","PRISMARINE",168,2),
    
    PRISMARINE_SHARD("logic/resources/items/"+"prismarine_shard.png","PRISMARINE_SHARD",409,0),
    PRISMARINE_CRYSTALS("logic/resources/items/"+"prismarine_crystals.png","PRISMARINE_CRYSTALS",410,0),
    
    PACKED_ICE("logic/resources/items/"+"packed_ice.png","PACKED_ICE",174,0),
    PAINTING("logic/resources/items/"+"painting.png","PAINTING",321,0),
    PAPER("logic/resources/items/"+"paper.png","PAPER",339,0),
    FURNACE_MINECART("logic/resources/items/"+"furnace_minecart.png","FURNACE_MINECART",343,0),
    PUMPKIN_SEEDS("logic/resources/items/"+"pumpkin_seeds.png","PUMPKIN_SEEDS",361,0),
    
    POISONOUS_POTATO("logic/resources/items/"+"poisonous_potato.png","POISONOUS_POTATO",394,0),
    PUMPKIN_PIE("logic/resources/items/"+"pumpkin_pie.png","PUMPKIN_PIE",400,0),
    
    QUARTZ("logic/resources/items/"+"quartz.png","QUARTZ",406,0),
    QUARTZ_ORE("logic/resources/items/"+"quartz_ore.png","QUARTZ_ORE",153,0),
    
    QUARTZ_BLOCK("logic/resources/items/"+"quartz_block.png","QUARTZ_BLOCK",155,0),
    CHISELED_QUARTZ_BLOCK("logic/resources/items/"+"quartz_block_1.png","QUARTZ_BLOCK",155,1),
    PILLAR_QUARTZ_BLOCK("logic/resources/items/"+"quartz_block_2.png","QUARTZ_BLOCK",155,2),
    
    
    QUARTZ_STAIRS("logic/resources/items/"+"quartz_stairs.png","QUARTZ_STAIRS",156,0),
    RAIL("logic/resources/items/"+"rail.png","RAIL",66,0),
    
    DANDELION("logic/resources/items/"+"yellow_flower.png","YELLOW_FLOWER",37,0),
    POPPY("logic/resources/items/"+"red_flower.png","RED_FLOWER",38,0),
    BLUE_ORCHID("logic/resources/items/"+"red_flower_1.png","RED_FLOWER",38,1),
    ALLIUM("logic/resources/items/"+"red_flower_2.png","RED_FLOWER",38,2),
    AZURE_BLUET("logic/resources/items/"+"red_flower_3.png","RED_FLOWER",38,3),
    RED_TULIP("logic/resources/items/"+"red_flower_4.png","RED_FLOWER",38,4),
    ORANGE_TULIP("logic/resources/items/"+"red_flower_5.png","RED_FLOWER",38,5),
    WHITE_TULIP("logic/resources/items/"+"red_flower_6.png","RED_FLOWER",38,6),
    PINK_TULIP("logic/resources/items/"+"red_flower_7.png","RED_FLOWER",38,7),
    OXEYE_DAISY("logic/resources/items/"+"red_flower_8.png","RED_FLOWER",38,8),
    
    RED_MUSHROOM("logic/resources/items/"+"red_mushroom.png","RED_MUSHROOM",40,0),
    REDSTONE_BLOCK("logic/resources/items/"+"redstone_block.png","REDSTONE_BLOCK",152,0),
    REDSTONE_LAMP("logic/resources/items/"+"redstone_lamp.png","REDSTONE_LAMP",123,0),
    REDSTONE_ORE("logic/resources/items/"+"redstone_ore.png","REDSTONE_ORE",73,0),
    REDSTONE_TORCH("logic/resources/items/"+"redstone_torch.png","REDSTONE_TORCH",76,0),
    
    RED_SANDSTONE("logic/resources/items/"+"red_sandstone.png","RED_SANDSTONE",179,0),
    CHISELED_RED_SANDSTONE("logic/resources/items/"+"red_sandstone_1.png","RED_SANDSTONE",179,1),
    SMOOTH_RED_SANDSTONE("logic/resources/items/"+"red_sandstone_2.png","RED_SANDSTONE",179,2),
    
    RED_SANDSTONE_STAIRS("logic/resources/items/"+"red_sandstone_stairs.png","RED_SANDSTONE_STAIRS",180,0),
    REDSTONE_DUST("logic/resources/items/"+"redstone.png","REDSTONE",331,0),
    REDSTONE_COMPARATOR("logic/resources/items/"+"comparator.png","COMPARATOR",404,0),
    
    RAW_RABBIT("logic/resources/items/"+"rabbit.png","RABBIT",411,0),
    RABBIT_STEW("logic/resources/items/"+"rabbit_stew.png","RABBIT_STEW",413,0),
    RABBIT_FOOT("logic/resources/items/"+"rabbit_foot.png","RABBIT_FOOT",414,0),
    RABBIT_HIDE("logic/resources/items/"+"rabbit_hide.png","RABBIT_HIDE",415,0),
    
    RAW_FISH("logic/resources/items/"+"fish.png","FISH",349,0),
    RAW_SALMON("logic/resources/items/"+"fish_1.png","FISH",349,1),
    RAW_CLOWNFISH("logic/resources/items/"+"fish_2.png","FISH",349,2),
    RAW_PUFFERFISH("logic/resources/items/"+"fish_3.png","FISH",349,3),
    RAW_BEEF("logic/resources/items/"+"beef.png","BEEF",363,0),
    RAW_CHICKEN("logic/resources/items/"+"chicken.png","CHICKEN",365,0),
    ROTTEN_FLESH("logic/resources/items/"+"rotten_flesh.png","ROTTEN_FLESH",367,0),

    STONE("logic/resources/items/"+"stone.png","STONE",1,0),
    GRANITE("logic/resources/items/"+"stone_1.png","STONE",1,1),
    POLISHED_GRANITE("logic/resources/items/"+"stone_2.png","STONE",1,2),
    DIORITE("logic/resources/items/"+"stone_3.png","STONE",1,3),
    POLISHED_DIORITE("logic/resources/items/"+"stone_4.png","STONE",1,4),
    ANDESITE("logic/resources/items/"+"stone_5.png","STONE",1,5),
    POLISHED_ANDESITE("logic/resources/items/"+"stone_6.png","STONE",1,6),

    OAK_SAPLING("logic/resources/items/"+"sapling.png","SAPLING",6,0),
    SPRUCE_SAPLING("logic/resources/items/"+"sapling_1.png","SAPLING",6,1),
    BIRCK_SAPLING("logic/resources/items/"+"sapling_2.png","SAPLING",6,2),
    JUNGLE_SAPLING("logic/resources/items/"+"sapling_3.png","SAPLING",6,3),
    ACACIA_SAPLING("logic/resources/items/"+"sapling_4.png","SAPLING",6,4),
    DARK_OAK_SAPLING("logic/resources/items/"+"sapling_5.png","SAPLING",6,5),

    STONE_SLAB("logic/resources/items/"+"stone_slab.png","STONE_SLAB",44,0),
    SANDTONE_SLAB("logic/resources/items/"+"stone_slab_1.png","STONE_SLAB",44,1),
    WOODEN_SLAB("logic/resources/items/"+"stone_slab_2.png","STONE_SLAB",44,2),
    COBBLESTONE_SLAB("logic/resources/items/"+"stone_slab_3.png","STONE_SLAB",44,3),
    BRICK_SLAB("logic/resources/items/"+"stone_slab_4.png","STONE_SLAB",44,4),
    STONE_BRICK_SLAB("logic/resources/items/"+"stone_slab_5.png","STONE_SLAB",44,5),
    NETHER_BRICK_SLAB("logic/resources/items/"+"stone_slab_6.png","STONE_SLAB",44,6),
    QUARTZ_SLAB("logic/resources/items/"+"stone_slab_7.png","STONE_SLAB",44,7),

    SAND("logic/resources/items/"+"sand.png","SAND",12,0),
    RED_SAND("logic/resources/items/"+"sand_1.png","SAND",12,1),
    
    SPONGE("logic/resources/items/"+"sponge.png","SPONGE",19,0),
    WET_SPONGE("logic/resources/items/"+"sponge_1.png","SPONGE",19,1),
    
    SANDSTONE("logic/resources/items/"+"sandstone.png","SANDSTONE",24,0),
    CHISELED_SANDSTONE("logic/resources/items/"+"sandstone_1.png","SANDSTONE",24,1),
    SMOOTH_SANDSTONE("logic/resources/items/"+"sandstone_2.png","SANDSTONE",24,2),
    
    STONE_PRESSURE_PLATE("logic/resources/items/"+"stone_pressure_plate.png","STONE_PLATE",70,0),
    STONE_BUTTON("logic/resources/items/"+"stone_button.png","STONE_BUTTON",77,0),
    
    SNOW("logic/resources/items/"+"snow_layer.png","SNOW_LAYER",78,0),
    SNOW_BLOCK("logic/resources/items/"+"snow.png","SNOW_BLOCK",80,0),
    SOUL_SAND("logic/resources/items/"+"soul_sand.png","SOUL_SAND",88,0),
    
    WHITE_STAINED_GLASS("logic/resources/items/"+"stained_glass.png","STAINED_GLASS",95,0),
    ORANGE_STAINED_GLASS("logic/resources/items/"+"stained_glass_1.png","STAINED_GLASS",95,1),
    MAGENTA_STAINED_GLASS("logic/resources/items/"+"stained_glass_2.png","STAINED_GLASS",95,2),
    LIGHT_BLUE_STAINED_GLASS("logic/resources/items/"+"stained_glass_3.png","STAINED_GLASS",95,3),
    YELLOW_STAINED_GLASS("logic/resources/items/"+"stained_glass_4.png","STAINED_GLASS",95,4),
    LIME_STAINED_GLASS("logic/resources/items/"+"stained_glass_5.png","STAINED_GLASS",95,5),
    PINK_STAINED_GLASS("logic/resources/items/"+"stained_glass_6.png","STAINED_GLASS",95,6),
    GRAY_STAINED_GLASS("logic/resources/items/"+"stained_glass_7.png","STAINED_GLASS",95,7),
    LIGHT_GRAY_STAINED_GLASS("logic/resources/items/"+"stained_glass_8.png","STAINED_GLASS",95,8),
    CYAN_STAINED_GLASS("logic/resources/items/"+"stained_glass_9.png","STAINED_GLASS",95,9),
    PURPLE_STAINED_GLASS("logic/resources/items/"+"stained_glass_10.png","STAINED_GLASS",95,10),
    BLUE_STAINED_GLASS("logic/resources/items/"+"stained_glass_11.png","STAINED_GLASS",95,11),
    BROWN_STAINED_GLASS("logic/resources/items/"+"stained_glass_12.png","STAINED_GLASS",95,12),
    GREEN_STAINED_GLASS("logic/resources/items/"+"stained_glass_13.png","STAINED_GLASS",95,13),
    RED_STAINED_GLASS("logic/resources/items/"+"stained_glass_14.png","STAINED_GLASS",95,14),
    BLACK_STAINED_GLASS("logic/resources/items/"+"stained_glass_15.png","STAINED_GLASS",95,15),

    SMOOTH_BRICK("logic/resources/items/"+"stonebrick.png","STONEBRICK",98,0),
    MOOSY_STONE_BRICK("logic/resources/items/"+"stonebrick_1.png","STONEBRICK",98,1),
    CRACKED_STONE_BRICK("logic/resources/items/"+"stonebrick_2.png","STONEBRICK",98,2),
    CHISELED_STONE_BRICK("logic/resources/items/"+"stonebrick_3.png","STONEBRICK",98,3),
    
    STONE_BRICK_STAIRS("logic/resources/items/"+"stone_brick_stairs.png","STONE_BRICK_STAIRS",109,0),
    SANDSTONE_STAIRS("logic/resources/items/"+"sandstone_stairs.png","SANDSTONE_STAIRS",128,0),
    SPRUCE_WOOD_STAIRS("logic/resources/items/"+"spruce_stairs.png","SPRUCE_STAIRS",134,0),
    
    WHITE_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay.png","STAINED_CLAY",159,0),
    ORANGE_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_1.png","STAINED_CLAY",159,1),
    MAGENTA_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_2.png","STAINED_CLAY",159,2),
    LIGHT_BLUE_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_3.png","STAINED_CLAY",159,3),
    YELLOW_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_4.png","STAINED_CLAY",159,4),
    LIME_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_5.png","STAINED_CLAY",159,5),
    PINK_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_6.png","STAINED_CLAY",159,6),
    GRAY_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_7.png","STAINED_CLAY",159,7),
    LIGHT_GRAY_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_8.png","STAINED_CLAY",159,8),
    CYAN_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_9.png","STAINED_CLAY",159,9),
    PURPLE_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_10.png","STAINED_CLAY",159,10),
    BLUE_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_11.png","STAINED_CLAY",159,11),
    BROWN_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_12.png","STAINED_CLAY",159,12),
    GREEN_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_13.png","STAINED_CLAY",159,13),
    RED_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_14.png","STAINED_CLAY",159,14),
    BLACK_STAINED_CLAY("logic/resources/items/"+"stained_hardened_clay_15.png","STAINED_CLAY",159,15),
    
    WHITE_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane.png","STAINED_GLASS_PANE",160,0),
    ORANGE_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_1.png","STAINED_GLASS_PANE",160,1),
    MAGENTA_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_2.png","STAINED_GLASS_PANE",160,2),
    LIGHT_BLUE_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_3.png","STAINED_GLASS_PANE",160,3),
    YELLOW_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_4.png","STAINED_GLASS_PANE",160,4),
    LIME_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_5.png","STAINED_GLASS_PANE",160,5),
    PINK_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_6.png","STAINED_GLASS_PANE",160,6),
    GRAY_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_7.png","STAINED_GLASS_PANE",160,7),
    LIGHT_GRAY_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_8.png","STAINED_GLASS_PANE",160,8),
    CYAN_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_9.png","STAINED_GLASS_PANE",160,9),
    PURPLE_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_10.png","STAINED_GLASS_PANE",160,10),
    BLUE_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_11.png","STAINED_GLASS_PANE",160,11),
    BROWN_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_12.png","STAINED_GLASS_PANE",160,12),
    GREEN_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_13.png","STAINED_GLASS_PANE",160,13),
    RED_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_14.png","STAINED_GLASS_PANE",160,14),
    BLACK_STAINED_GLASS_PANE("logic/resources/items/"+"stained_glass_pane_15.png","STAINED_GLASS_PANE",160,15),
    
    SEA_LANTERN("logic/resources/items/"+"sea_lantern.png","SEA_LANTERN",169,0),
    RED_STONE_SLAB("logic/resources/items/"+"stone_slab2.png","STONE_SLAB2",182,0),
    
    SPRUCE_FENCE_GATE("logic/resources/items/"+"spruce_fence_gate.png","SPRUCE_FENCE_GATE",183,0),
    SPRUCE_FENCE("logic/resources/items/"+"spruce_fence.png","SPRUCE_FENCE",188,0),
    
    STICK("logic/resources/items/"+"stick.png","STICK",280,0),
    STRING("logic/resources/items/"+"string.png","STRING",287,0),
    GUNPOWDER("logic/resources/items/"+"gunpowder.png","SULPHUR",289,0),
    SIGN("logic/resources/items/"+"sign.png","SIGN",323,0),
    
    WHEAT_SEEDS("logic/resources/items/"+"wheat_seeds.png","SEEDS",295,0),
    SADDLE("logic/resources/items/"+"saddle.png","SADDLE",329,0),
    SNOW_BALL("logic/resources/items/"+"snowball.png","SNOW_BALL",332,0),
    SUGAR_CANE("logic/resources/items/"+"reeds.png","SUGAR_CANE",338,0),
    SLIME_BALL("logic/resources/items/"+"slimeball.png","SLIME_BALL",341,0),
    STORAGE_MINECART("logic/resources/items/"+"chest_minecart.png","STORAGE_MINECART",342,0),
    SUGAR("logic/resources/items/"+"sugar.png","SUGAR",353,0),
    SHEARS("logic/resources/items/"+"shears.png","SHEARS",359,0),
    SPIDER_EYE("logic/resources/items/"+"spider_eye.png","SPIDER_EYE",375,0),
    SPECKLED_MELON("logic/resources/items/"+"speckled_melon.png","SPECKLED_MELON",382,0),
    
    SKELETON_SKULL("logic/resources/items/"+"skull.png","SKULL_ITEM",397,0),
    WITHER_SKULL("logic/resources/items/"+"skull_1.png","SKULL_ITEM",397,1),
    ZOMBIE_SKULL("logic/resources/items/"+"skull_2.png","SKULL_ITEM",397,2),
    STEVE_SKULL("logic/resources/items/"+"skull_3.png","SKULL_ITEM",397,3),
    CREEPER_SKULL("logic/resources/items/"+"skull_4.png","SKULL_ITEM",397,4),
    
    SPRUCE_DOOR("logic/resources/items/"+"spruce_door.png","SPRUCE_DOOR",427,0),
    TRAP_DOOR("logic/resources/items/"+"trapdoor.png","TRAP_DOOR",96,0),
    THIN_GLASS("logic/resources/items/"+"glass_pane.png","THIN_GLASS",102,0),
    TRAPPED_CHEST("logic/resources/items/"+"trapped_chest.png","TRAPPED_CHEST",146,0),
    TRIPWIRE_HOOK("logic/resources/items/"+"tripwire_hook.png","TRIPWIRE_HOOK",131,0),
    TNT("logic/resources/items/"+"tnt.png","TNT",46,0),
    TORCH("logic/resources/items/"+"torch.png","TORCH",50,0),
    VINE("logic/resources/items/"+"vine.png","VINE",106,0),
    
    OAK_WOOD("logic/resources/items/"+"planks.png","WOOD",5,0),
    SPRUCE_WOOD("logic/resources/items/"+"planks_1.png","WOOD",5,1),
    BIRCH_WOOD("logic/resources/items/"+"planks_2.png","WOOD",5,2),
    JUNGLE_WOOD("logic/resources/items/"+"planks_3.png","WOOD",5,3),
    ACACIA_WOOD("logic/resources/items/"+"planks_4.png","WOOD",5,4),
    DARK_OAK_WOOD("logic/resources/items/"+"planks_5.png","WOOD",5,5),
    
    COBWEB("logic/resources/items/"+"web.png","WEB",30,0),
    
    WHITE_WOOL("logic/resources/items/"+"wool.png","WOOL",35,0),
    ORANGE_WOOL("logic/resources/items/"+"wool_1.png","WOOL",35,1),
    MAGENTA_WOOL("logic/resources/items/"+"wool_2.png","WOOL",35,2),
    LIGHT_BLUE_WOOL("logic/resources/items/"+"wool_3.png","WOOL",35,3),
    YELLOW_WOOL("logic/resources/items/"+"wool_4.png","WOOL",35,4),
    LIME_WOOL("logic/resources/items/"+"wool_5.png","WOOL",35,5),
    PINK_WOOL("logic/resources/items/"+"wool_6.png","WOOL",35,6),
    GRAY_WOOL("logic/resources/items/"+"wool_7.png","WOOL",35,7),
    LIGHT_GRAY_WOOL("logic/resources/items/"+"wool_8.png","WOOL",35,8),
    CYAN_WOOL("logic/resources/items/"+"wool_9.png","WOOL",35,9),
    PURPLE_WOOL("logic/resources/items/"+"wool_10.png","WOOL",35,10),
    BLUE_WOOL("logic/resources/items/"+"wool_11.png","WOOL",35,11),
    BROWN_WOOL("logic/resources/items/"+"wool_12.png","WOOL",35,12),
    GREEN_WOOL("logic/resources/items/"+"wool_13.png","WOOL",35,13),
    RED_WOOL("logic/resources/items/"+"wool_14.png","WOOL",35,14),
    BLACK_WOOL("logic/resources/items/"+"wool_15.png","WOOL",35,15),
    
    OAK_STAIRS("logic/resources/items/"+"oak_stairs.png","WOOD_STAIRS",53,0),
    WORKBENCH("logic/resources/items/"+"crafting_table.png","WORKBENCH",58,0),
    OAK_DOOR("logic/resources/items/"+"wooden_door.png","WOOD_DOOR",324,0),
    WOOD_PLATE("logic/resources/items/"+"wooden_pressure_plate.png","WOOD_PLATE",72,0),
    WATER_LILY("logic/resources/items/"+"waterlily.png","WATER_LILY",111,0),
    
    OAK_WOOD_SLAB("logic/resources/items/"+"wooden_slab.png","WOOD_STEP",126,0),
    SPRUCE_WOOD_SLAB("logic/resources/items/"+"wooden_slab_1.png","WOOD_STEP",126,1),
    BIRCH_WOOD_SLAB("logic/resources/items/"+"wooden_slab_2.png","WOOD_STEP",126,2),
    JUNGLE_WOOD_SLAB("logic/resources/items/"+"wooden_slab_3.png","WOOD_STEP",126,3),
    ACACIA_WOOD_SLAB("logic/resources/items/"+"wooden_slab_4.png","WOOD_STEP",126,4),
    DARK_OAK_WOOD_SLAB("logic/resources/items/"+"wooden_slab_5.png","WOOD_STEP",126,5),
    
    WOOD_BUTTON("logic/resources/items/"+"wooden_button.png","WOOD_BUTTON",143,0),

    
    WHEAT("logic/resources/items/"+"wheat.png","WHEAT",296,0),
    WATER_BUCKET("logic/resources/items/"+"water_bucket.png","WATER_BUCKET",326,0),
    WRITTEN_BOOK("logic/resources/items/"+"written_book.png","WRITTEN_BOOK",387,0),
    WATCH("logic/resources/items/"+"clock.png","WATCH",347,0),
    
    WATER_BOTTLE("logic/resources/items/"+"water_bottle.png","POTION",373,0),
    LEATHER_HELMET("logic/resources/items/"+"leather_helmet.png","LEATHER_HELMET",298,0),
    LEATHER_CHESTPLATE("logic/resources/items/"+"leather_chestplate.png","LEATHER_CHESTPLATE",299,0),
    LEATHER_LEGGINGS("logic/resources/items/"+"leather_leggings.png","LEATHER_LEGGINGS",300,0),
    LEATHER_BOOTS("logic/resources/items/"+"leather_boots.png","LEATHER_BOOTS",301,0),
    
    IRON_HELMET("logic/resources/items/"+"iron_helmet.png","IRON_HELMET",306,0),
    IRON_CHESTPLATE("logic/resources/items/"+"iron_chestplate.png","IRON_CHESTPLATE",307,0),
    IRON_LEGGINGS("logic/resources/items/"+"iron_leggings.png","IRON_LEGGINGS",308,0),
    IRON_BOOTS("logic/resources/items/"+"iron_boots.png","IRON_BOOTS",309,0),
    
    GOLD_HELMET("logic/resources/items/"+"gold_helmet.png","GOLDEN_HELMET",314,0),
    GOLD_CHESTPLATE("logic/resources/items/"+"gold_chestplate.png","GOLDEN_CHESTPLATE",315,0),
    GOLD_LEGGINGS("logic/resources/items/"+"gold_leggings.png","GOLDEN_LEGGINGS",316,0),
    GOLD_BOOTS("logic/resources/items/"+"gold_boots.png","GOLDEN_BOOTS",317,0),
    
    DIAMOND_HELMET("logic/resources/items/"+"diamond_helmet.png","DIAMOND_HELMET",310,0),
    DIAMOND_CHESTPLATE("logic/resources/items/"+"diamond_chestplate.png","DIAMOND_CHESTPLATE",311,0),
    DIAMOND_LEGGINGS("logic/resources/items/"+"diamond_leggings.png","DIAMOND_LEGGINGS",312,0),
    DIAMOND_BOOTS("logic/resources/items/"+"diamond_boots.png","DIAMOND_BOOTS",313,0),
    
    CHAINMAIL_HELMET("logic/resources/items/"+"chainmail_helmet.png","CHAINMAIL_HELMET",302,0),
    CHAINMAIL_CHESTPLATE("logic/resources/items/"+"chainmail_chestplate.png","CHAINMAIL_CHESTPLATE",303,0),
    CHAINMAIL_LEGGINGS("logic/resources/items/"+"chainmail_leggings.png","CHAINMAIL_LEGGINGS",304,0),
    CHAINMAIL_BOOTS("logic/resources/items/"+"chainmail_boots.png","CHAINMAIL_BOOTS",305,0),
    WOOD_SWORD("logic/resources/items/"+"wooden_sword.png","WOOD_SWORD",268,0),
    WOOD_SPADE("logic/resources/items/"+"wooden_shovel.png","WOOD_SPADE",269,0),
    WOOD_PICKAXE("logic/resources/items/"+"wooden_pickaxe.png","WOOD_PICKAXE",270,0),
    WOOD_AXE("logic/resources/items/"+"wooden_axe.png","WOOD_AXE",271,0),
    WOOD_HOE("logic/resources/items/"+"wooden_hoe.png","WOOD_HOE",290,0),
    
    STONE_SWORD("logic/resources/items/"+"stone_sword.png","STONE_SWORD",272,0),
    STONE_SHOVEL("logic/resources/items/"+"stone_shovel.png","STONE_SHOVEL",273,0),
    STONE_PICKAXE("logic/resources/items/"+"stone_pickaxe.png","STONE_PICKAXE",274,0),
    STONE_AXE("logic/resources/items/"+"stone_axe.png","STONE_AXE",275,0),
    STONE_HOE("logic/resources/items/"+"stone_hoe.png","STONE_HOE",291,0),
    
    IRON_SPADE("logic/resources/items/"+"iron_shovel.png","IRON_SHOVEL",256,0),
    IRON_PICKAXE("logic/resources/items/"+"iron_pickaxe.png","IRON_PICKAXE",257,0),
    IRON_AXE("logic/resources/items/"+"iron_axe.png","IRON_AXE",258,0),
    IRON_SWORD("logic/resources/items/"+"iron_sword.png","IRON_SWORD",267,0),
    IRON_HOE("logic/resources/items/"+"iron_hoe.png","IRON_HOE",292,0),
    
    DIAMOND_SWORD("logic/resources/items/"+"diamond_sword.png","DIAMOND_SWORD",276,0),
    DIAMOND_SHOVEL("logic/resources/items/"+"diamond_shovel.png","DIAMOND_SPADE",277,0),
    DIAMOND_PICKAXE("logic/resources/items/"+"diamond_pickaxe.png","DIAMOND_PICKAXE",278,0),
    DIAMOND_AXE("logic/resources/items/"+"diamond_axe.png","DIAMOND_AXE",279,0),
    DIAMOND_HOE("logic/resources/items/"+"diamond_hoe.png","DIAMOND_HOE",293,0),
    
    GOLD_HOE("logic/resources/items/"+"golden_hoe.png","GOLDEN_HOE",294,0),
    GOLD_SWORD("logic/resources/items/"+"golden_sword.png","GOLDEN_SWORD",283,0),
    GOLD_SPADE("logic/resources/items/"+"golden_shovel.png","GOLDEN_SHOVEL",284,0),
    GOLD_PICKAXE("logic/resources/items/"+"golden_pickaxe.png","GOLDEN_PICKAXE",285,0),
    GOLD_AXE("logic/resources/items/"+"golden_axe.png","GOLDEN_AXE",286,0),
    
    AWKWARD_POTION("logic/resources/items/"+"water_bottle.png","POTION",373,16),
    THICK_POTION("logic/resources/items/"+"water_bottle.png","POTION",373,32),
    MUNDANE_POTION("logic/resources/items/"+"water_bottle.png","POTION",373,64),
    REGENERATION_POTION("logic/resources/items/"+"potion_pink.png","POTION",373,8193),
    SWIFTNESS_POTION("logic/resources/items/"+"potion_light_blue.png","POTION",373,8194),
    FIRE_RESISTANCE_POTION("logic/resources/items/"+"potion_orange.png","POTION",373,8195),
    POISON_POTION("logic/resources/items/"+"potion_green.png","POTION",373,8196),
    HEALING_POTION("logic/resources/items/"+"potion_magenta.png","POTION",373,8197),
    NIGHT_VISION_POTION("logic/resources/items/"+"potion_blue.png","POTION",373,8198),
    WEAKNESS_POTION("logic/resources/items/"+"potion_gray.png","POTION",373,8200),
    STRENGTH_POTION("logic/resources/items/"+"potion_purple.png","POTION",373,8201),
    SLOWNESS_POTION("logic/resources/items/"+"potion_cyan.png","POTION",373,8202),
    HARMING_POTION("logic/resources/items/"+"potion_dark_purple.png","POTION",373,8204),
    WATER_BREATHING_POTION("logic/resources/items/"+"potion_blue2.png","POTION",373,8205),
    INVISIBILITY_POTION("logic/resources/items/"+"potion_light_purple.png","POTION",373,8206),
    REGENERATION_POTION_II("logic/resources/items/"+"potion_pink.png","POTION",373,8225),
    SWIFTNESS_POTION_II("logic/resources/items/"+"potion_light_blue.png","POTION",373,8226),
    POSION_POTION_II("logic/resources/items/"+"potion_green.png","POTION",373,8228),
    HEALING_POTION_II("logic/resources/items/"+"potion_magenta.png","POTION",373,8229),
    STRENGTH_POTION_II("logic/resources/items/"+"potion_purple.png","POTION",373,8233),
    LEAPING_POTION_II("logic/resources/items/"+"potion_light_cyan.png","POTION",373,8235),
    HARMING_POTION_II("logic/resources/items/"+"potion_dark_purple.png","POTION",373,8236),
    REGENERATION_POTION_2M("logic/resources/items/"+"potion_pink.png","POTION",373,8257),
    SWIFTNESS_POTION_8M("logic/resources/items/"+"potion_light_blue.png","POTION",373,8258),
    FIRE_RESISTANCE_POTION_8M("logic/resources/items/"+"potion_orange.png","POTION",373,8259),
    POISON_POTION_2M("logic/resources/items/"+"potion_green.png","POTION",373,8260),
    NIGHT_VISION_POTION_8M("logic/resources/items/"+"potion_blue.png","POTION",373,8262),
    WEAKNESS_POTION_4M("logic/resources/items/"+"potion_gray.png","POTION",373,8264),
    STRENGTH_POTION_8M("logic/resources/items/"+"potion_purple.png","POTION",373,8265),
    SLOWNESS_POTION_4M("logic/resources/items/"+"potion_cyan.png","POTION",373,8266),
    LEAPING_POTION_3M("logic/resources/items/"+"potion_light_cyan.png","POTION",373,8267),
    WATER_BREATHING_POTION_8M("logic/resources/items/"+"potion_blue2.png","POTION",373,8269),
    INVISIBILITY_POTION_8M("logic/resources/items/"+"potion_light_purple.png","POTION",373,8270),
    REGENERATION_POTION_II_1M("logic/resources/items/"+"potion_pink.png","POTION",373,8289),
    SWIFTNESS_POTION_II_4M("logic/resources/items/"+"potion_light_blue.png","POTION",373,8290),
    POISON_POTION_II_1M("logic/resources/items/"+"potion_green.png","POTION",373,8292),
    STRENGTH_POTION_II_4M("logic/resources/items/"+"potion_purple.png","POTION",373,8297),
    
    REGENERATION_SPLASH_33S("logic/resources/items/"+"splash_potion_pink.png","POTION",373,16385),
    SWIFTNESS_SPLASH_2M15("logic/resources/items/"+"splash_potion_light_blue.png","POTION",373,16386),
    FIRE_RESISTANCE_SPLASH_2M15("logic/resources/items/"+"splash_potion_orange.png","POTION",373,16387),
    POISON_SPLASH_33S("logic/resources/items/"+"splash_potion_green.png","POTION",373,16388),
    HEALING_SPLASH("logic/resources/items/"+"splash_potion_magenta.png","POTION",373,16389),
    NIGHT_VISION_SPLASH_2M15("logic/resources/items/"+"splash_potion_blue.png","POTION",373,16390),
    WEAKNESS_SPLASH_1M07("logic/resources/items/"+"splash_potion_gray.png","POTION",373,16392),
    STRENGTH_SPLASH_2M15("logic/resources/items/"+"splash_potion_purple.png","POTION",373,16393),
    SLOWNESS_SPLASH_1M07("logic/resources/items/"+"splash_potion_light_blue.png","POTION",373,16394),
    HARMING_SPLASH("logic/resources/items/"+"splash_potion_dark_purple.png","POTION",373,16396),
    BREATHING_SPLASH_2M15("logic/resources/items/"+"splash_potion_blue2.png","POTION",373,16397),
    INVISIBILITY_SPLASH_2M15("logic/resources/items/"+"splash_potion_light_gray.png","POTION",373,16398),
    REGENERATION_SPLASH_II_16S("logic/resources/items/"+"splash_potion_pink.png","POTION",373,16417),
    SWITNESS_SPLASH_II_1M07("logic/resources/items/"+"splash_potion_light_blue.png","POTION",373,16418),
    POISON_SPLASH_II_16S("logic/resources/items/"+"splash_potion_green.png","POTION",373,16420),
    HEALING_SPLASH_II("logic/resources/items/"+"splash_potion_magenta.png","POTION",373,16421),
    STRENGTH_SPLASH_II_1M07("logic/resources/items/"+"splash_potion_purple.png","POTION",373,16425),
    LEAPING_SPLASH_II_1M07("logic/resources/items/"+"splash_potion_light_cyan.png","POTION",373,16427),
    HARMING_SPLASH_II("logic/resources/items/"+"splash_potion_dark_purple.png","POTION",373,16428),
    REGENERATION_SPLASH_1M30("logic/resources/items/"+"splash_potion_pink.png","POTION",373,16449),
    SWIFTNESS_SPLASH_6M("logic/resources/items/"+"splash_potion_light_blue.png","POTION",373,16450),
    FIRE_RESISTANCE_SPLASH_6M("logic/resources/items/"+"splash_potion_orange.png","POTION",373,16451),
    POISON_SPLASH_1M30("logic/resources/items/"+"splash_potion_green.png","POTION",373,16452),
    NIGHT_VISION_SPLASH_6M("logic/resources/items/"+"splash_potion_blue.png","POTION",373,16454),
    WEAKNESS_SPLASH_3M("logic/resources/items/"+"splash_potion_gray.png","POTION",373,16456),
    STRENGTH_SPLASH_6M("logic/resources/items/"+"splash_potion_purple.png","POTION",373,16457),
    SLOWNESS_SPLASH_3M("logic/resources/items/"+"splash_potion_light_blue.png","POTION",373,16458),
    LEAPING_SPLASH_2M15("logic/resources/items/"+"splash_potion_light_cyan.png","POTION",373,16459),
    BREATHING_SPLASH_6M("logic/resources/items/"+"splash_potion_blue2.png","POTION",373,16461),
    INVISIBILITY_SPLASH_6M("logic/resources/items/"+"splash_potion_light_gray.png","POTION",373,16462),
    REGENERATION_SPLASH_II_45S("logic/resources/items/"+"splash_potion_pink.png","POTION",373,16481),
    SWIFTNESS_SPLASH_II_3M("logic/resources/items/"+"splash_potion_light_blue.png","POTION",373,16482),
    POISON_SPLASH_II_45S("logic/resources/items/"+"splash_potion_green.png","POTION",373,16484),
    STRENGTH_SPLASH_II_3M("logic/resources/items/"+"splash_potion_purple.png","POTION",373,16489);
    
   String path;
    String material;
    int id;
    int datavalue;
   

    private EnumQuestItems(String path,String mat,int id,int datavalue) {
        this.path = path;
        this.material=mat;
        this.id=id;
        this.datavalue=datavalue;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getMaterial() {
        return material;
    }

    public void setMaterial(String material) {
        this.material = material;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getDatavalue() {
        return datavalue;
    }

    public void setDatavalue(int datavalue) {
        this.datavalue = datavalue;
    }
}