breakprobability: 0.3
detteroriateprobability: 0.4
nothingprobability: 0.6
improveprobability: 1.0
weapon:
    material: DIAMOND
    name: Weapon Upgrader
    lores:
        - Toma el objeto y aplicalo a un arma
        - Mucha suerte!!!